api_platform:
    title: API discovery
    version: 1.0.0
    show_webby: false
    description: API destinée à la découverte de la plateforme API Platform
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/ressources']
    formats:
        jsonld: ['application/ld+json','application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
