App\ApiResource\SimpleCalculatorRequest:
  attributes:
    operation:
      type: enum
      enum:
          - 'add'
          - 'sub'
          - 'mul'
          - 'div'
      example: 'add'
      description: 'The operation to perform'
      groups: [ 'simple_calculator_request:write']

    firstOperand:
      type: integer
      example: 1
      description: 'The first operand'
      groups: [ 'simple_calculator_request:write']

    secondOperand:
      type: integer
      example: 1
      description: 'The second operand'
      groups: [ 'simple_calculator_request:write' ]

    result:
        type: integer
        example: 2
        description: 'The result of the operation'
        groups: [ 'simple_calculator_request:read' ]